# Generated by Django 2.1.2 on 2018-10-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181015_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sample',
        ),
    ]
