# Generated by Django 2.1.2 on 2018-10-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_question_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='No Title', max_length=10),
        ),
    ]
